---
all:
  vars:
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    client1:
      ansible_host: 192.168.1.167
    client2:
      ansible_host: 192.168.1.168
  vars:
    ansible_password: admin
    env: 'production'      
