---
- name: Install apache with docker on Centos
  become: true
  hosts: prod

  pre_tasks:
    - name: Update cache
      yum:
        update_cache: yes

    - name: install package with yum
      yum:
        name: '{{ item }}'
        state: present
      loop:
        - epel-release
        - git
        - wget
      when: ansible_distribution ==  'CentOS'



  tasks:
    - name: install Python and pip3
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker SDK for python
      pip:
        name: docker
        executable: pip3

    - name: Install requests library
      pip:
        name: requests
        executable: pip3


    - name: Download script to install docker
      get_url:
        url: "https://get.docker.com/"
        dest: /tmp/get-docker.sh
        mode: "0755"
      when: ansible_facts['distribution'] == "CentOS"

    - name: Execute script
      command: "/tmp/get-docker.sh"

    - name: add user in groups docker
      user:
        name: admin
        groups: docker
        append: yes

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copy index.html to container
      template:
        src: index.html.j2
        dest: /tmp/index.html

    - name: Run container apache
      community.docker.docker_container:
        name: apache
        image: httpd
        state: started
        ports:
          - "80:80"
        volumes:
          - /tmp/index.html:/usr/local/apache2/htdocs/index.html

